<?php
/**
 * Fishpig's Attribute Splash 
 *
 * @category    Fishpig
 * @package    Fishpig_AttributeSplash
 * @author      Ben Tideswell <ben@fishpig.co.uk>
 */
 ?>
<?php if ($attribute = $this->getAttribute()): ?>
	<div class="page-title category-title">
		<h1><a href="<?php echo $attribute->getUrl() ?>" title="<?php echo $this->htmlEscape($attribute->getName()) ?>"><?php echo $this->htmlEscape($attribute->getName()) ?></a></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<?php echo $this->getPagerHtml() ?>
	<?php $splashes = $attribute->getSplashPages() ?>
	<?php if ($this->isGridMode()): ?>
		<?php $_columnCount = $this->getColumnCount() ?>
		<?php $_collectionSize = $splashes->count() ?>
		<?php $i = 0; foreach($splashes as $splash): ?>
			<?php if ($i++%$_columnCount==0): ?>
				<ul class="products-grid">
			<?php endif ?>
			<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<a href="<?php echo $splash->getUrl() ?>" title="<?php echo $this->htmlEscape($splash->getName()) ?>" class="product-image"><img src="<?php echo $splash->getThumbnailUrl() ?>" alt="<?php echo $this->htmlEscape($splash->getName()) ?>" /></a>
				<h2 class="product-name"><a href="<?php echo $splash->getUrl() ?>" title="<?php echo $this->htmlEscape($splash->getName()) ?>"><?php echo $this->htmlEscape($splash->getName()) ?></a></h2>
			</li>
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
				</ul>
			<?php endif ?>
		<?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	<?php elseif ($this->isListMode()): ?>
		<ol id="splash-list" class="products-list">
			<?php foreach($splashes as $splash): ?>
				<li class="item">
					<a class="product-image" title="<?php echo $this->htmlEscape($splash->getDisplayName()) ?>" href="<?php echo $splash->getUrl() ?>">
						<img alt="<?php echo $this->htmlEscape($splash->getDisplayName()) ?>" src="<?php echo $splash->getThumbnailUrl() ?>"/>
					</a>
					<div class="product-shop">
						<div class="f-fix">
							<h2 class="product-name"><a title="<?php echo $this->htmlEscape($splash->getDisplayName()) ?>" href="<?php echo $splash->getUrl() ?>"><?php echo $this->htmlEscape($splash->getDisplayName()) ?></a></h2>
							<div class="desc std"><?php echo $splash->getShortDescription() ?> <a class="link-more" title="<?php echo $this->htmlEscape($splash->getDisplayName()) ?>" href="<?php echo $splash->getUrl() ?>"><?php echo $this->__('View Products') ?></a></div>
						</div>
					</div>
				</li>
			<?php endforeach; ?>
		</ol>
		<script type="text/javascript">decorateList('splash-list', 'non-recursive');</script>
	<?php elseif ($this->isSimpleMode()): ?>
		<ul>
			<?php foreach($splashes as $splash): ?>
				<li>
					<a href="<?php echo $splash->getUrl() ?>" title="<?php echo $this->htmlEscape($splash->getDisplayName()) ?>"><?php echo $this->htmlEscape($splash->getDisplayName()) ?></a>

				</li>
			<?php endforeach; ?>
		</ul>
	<?php endif; ?>
	<?php echo $this->getPagerHtml() ?>
<?php endif; ?>