<?php
/**
 * Fishpig's Attribute Splash 
 *
 * @category    Fishpig
 * @package    Fishpig_AttributeSplash
 * @author      Ben Tideswell <ben@fishpig.co.uk>
 */
 ?>
<?php if ($splash = $this->getSplash()): ?>
	<div class="page-title category-title">
		<h1><a href="<?php echo $splash->getUrl() ?>" title="<?php echo $this->htmlEscape($splash->getName()) ?>"><?php echo $this->htmlEscape($splash->getName()) ?></a></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<?php if ($splash->getImage()): ?>
		<p class="category-image">
			<img src="<?php echo $splash->getImageUrl() ?>" alt="<?php echo $this->htmlEscape($splash->getName()) ?>"/>
		</p>
	<?php endif; ?>
	<?php if ($shortDescription = $splash->getShortDescription()): ?>
		<div class="category-description std"><?php echo $shortDescription ?></div>
	<?php endif; ?>
	<?php if($this->isContentMode()): ?>
		<?php echo $this->getCmsBlockHtml() ?>
	<?php elseif($this->isMixedMode()): ?>
		<?php echo $this->getCmsBlockHtml() ?>
		<?php echo $this->getProductListHtml() ?>
	<?php else: ?>
		<?php echo $this->getProductListHtml() ?>
	<?php endif; ?>
<?php endif; ?>