<?php
/**
 * @category    Fishpig
 * @package     Fishpig_AttributeSplash
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <h2><?php echo $this->__('Additional Information') ?></h2>
    <table class="data-table" id="product-attribute-specs-table">
        <col width="25%" />
        <col />
        <tbody>
        <?php foreach ($_additional as $_data): ?>
            <tr>
                <th class="label"><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
                <td class="data">
                	<?php if (isset($_data['link'])): ?>
                		<a href="<?php echo $_data['link'] ?>"<?php if (isset($_data['title'])): ?> title="<?php echo $this->escapeHtml($_data['title']) ?>"<?php endif; ?>>
                	<?php endif; ?>
                	<?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                	<?php if (isset($_data['link'])): ?>
                		</a>
                	<?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
<?php endif;?>
