<?php
/**
*
*/
?>
<?php if ($this->hasAvailableAddons()): ?>
<div id="splash-addons">
	<ul id="splash-addons-list">
		<?php foreach($this->getAvailableAddons() as $addon): ?>
			<li class="item">
				<div class="pad">
					<a href="<?php echo $addon->getTrackedUrl() ?>" target="_blank" class="image">
						<img src="<?php echo $addon->getImage() ?>" alt="<?php echo $this->escapeHtml($addon->getTitle()) ?>" />
					</a>
					<h2>
						<a href="<?php echo $addon->getTrackedUrl() ?>" target="_blank">
							<strong><?php echo $this->escapeHtml($addon->getTitle()) ?></strong>
							<span><?php echo $this->escapeHtml($addon->getSubtitle()) ?></span>
						</a>
					</h2>
					<p><?php echo $addon->getDescription() ?></p>
					<div><a href="<?php echo $addon->getTrackedUrl() ?>" target="_blank"><?php echo $this->__('View Add-On') ?></a></div>
				</div>			
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<script type="text/javascript">decorateList('splash-addons-list')</script>
<style type="text/css">
#splash-addons { max-width: 1600px; margin: 50px auto 0; }
#splash-addons ul { height: 1%; overflow: hidden; }
#splash-addons li.item { float: left; width: 25%; text-align: center; }
#splash-addons li.item .pad { padding: 10% 8%; border-right: 1px solid #ccc; }
#splash-addons li.item.last .pad { border-right: 0px none; }
#splash-addons li.item .image { display: block; margin-bottom: 10px; }
#splash-addons h2 {}
#splash-addons h2 a { color: #000; text-decoration: none; font-family: Tahoma, Verdana, Arial;, }
#splash-addons h2 strong { display: block; text-transform: uppercase; line-height: 1em; }
#splash-addons h2 span { font-size: 75%; font-family: Georgia, 'Times New Roman'; font-style: italic; }
#splash-addons p { min-height: 80px; }
</style>
<?php endif; ?>
