<?php
/**
*
*/
?>
<?php if ($extensions = $this->getExtensions(4, array('Fishpig_CrossLink', 'Fishpig_AttributeSplashPro', 'Fishpig_NoBots'))): ?>
<div id="splash-addons">
	<ul id="splash-addons-list">
		<?php foreach($extensions as $extension): ?>
			<li class="item<?php if ($this->isLast($extension)): ?> last<?php endif; ?>">
				<div class="pad">
					<a href="<?php echo $this->getTrackedUrl($extension, 'Fishpig_AttributeSplash', 'image') ?>" class="image">
						<img src="<?php echo $this->getImageUrl($extension) ?>" alt="<?php echo $this->escapeHtml($this->getTitle($extension)) ?>" />
					</a>
					<h2>
						<a href="<?php echo $this->getTrackedUrl($extension, 'Fishpig_AttributeSplash', 'title') ?>">
							<strong><?php echo $this->escapeHtml($this->getTitle($extension)) ?></strong>
							<span><?php echo $this->escapeHtml($this->getSubTitle($extension)) ?></span>
						</a>
					</h2>
					<p><?php echo $this->getShortDescription($extension) ?></p>
					<div><a href="<?php echo $this->getTrackedUrl($extension, 'Fishpig_AttributeSplash', 'view-more') ?>"><?php echo $this->__('View Add-On') ?></a></div>
				</div>			
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<script type="text/javascript">$('splash-addons').select('a').invoke('writeAttribute', 'target', '_blank');</script>
<style type="text/css">
#splash-addons { max-width: 1600px; margin: 50px auto 0; }
#splash-addons ul { height: 1%; overflow: hidden; }
#splash-addons li.item { float: left; width: 25%; text-align: center; }
#splash-addons li.item .pad { padding: 10% 8%; border-right: 1px solid #ccc; }
#splash-addons li.item.last .pad { border-right: 0px none; }
#splash-addons li.item .image { display: block; margin-bottom: 10px; }
#splash-addons h2 {}
#splash-addons h2 a { color: #000; text-decoration: none; font-family: Tahoma, Verdana, Arial;, }
#splash-addons h2 strong { display: block; text-transform: uppercase; line-height: 1em; }
#splash-addons h2 span { font-size: 75%; font-family: Georgia, 'Times New Roman'; font-style: italic; }
#splash-addons p { min-height: 80px; }
</style>
<?php endif; ?>
