<?php
/**
 * Fishpig's Attribute Splash 
 *
 * @category    Fishpig
 * @package    Fishpig_AttributeSplash
 * @author      Ben Tideswell <ben@fishpig.co.uk>
 */
?>
<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
			<td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
		</tr>
	</table>
</div>
<div id="splash_grid_wrapper"></div>