<?php
/**
 * @category    Fishpig
 * @package     Fishpig_AttributeSplash
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($this->getRequest()->getParam('section') == 'attributeSplash'): ?>
	<script type="text/javascript">		
		var oldSuffix = $('attributeSplash_seo_url_suffix');
		
		$('config_edit_form').insert({bottom: '<input type="hidden" name="groups[seo][fields][url_suffix_old][value]" value="' + oldSuffix.getValue() + '" />'});
		
		var oldGroupUrlKey = $('attributeSplash_frontend_include_group_url_key');
		
		$('config_edit_form').insert({bottom: '<input type="hidden" name="groups[frontend][fields][include_group_url_key_old][value]" value="' + oldGroupUrlKey.getValue() + '" />'});
	</script>
<?php endif; ?>