<?php
/**
 * @category    Fishpig
 * @package     Fishpig_AttributeSplash
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($this->getRequest()->getParam('section') == 'attributeSplash'): ?>
	<script type="text/javascript">
		//<![CDATA[
		(function() {
			var oldSuffix = $('attributeSplash_seo_url_suffix').getValue();
			var oldGroupUrlKey = $('attributeSplash_frontend_include_group_url_key').getValue();
			
			configForm.oldSubmit = configForm.submit;
			
			configForm.submit = function() {
				var newSuffix = $('attributeSplash_seo_url_suffix').getValue();
				var newGroupUrlKey = $('attributeSplash_frontend_include_group_url_key').getValue();
				
				if (oldSuffix !== newSuffix || oldGroupUrlKey !== newGroupUrlKey) {
					$('config_edit_form').insert({bottom: '<input type="hidden" name="reindex_urls" value="1" />'});
				}
			
				this.oldSubmit();
			};
		})();
		//]]>
	</script>
<?php endif; ?>