<?php
/**
 * @category    Fishpig
 * @package     Fishpig_AttributeSplash
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($this->canDisplay()): ?>
	<?php if ($this->displaySplashPagesTogether()): ?>
		<?php $splashPages = $this->getAllSplashPages() ?>
		<?php $pageCount = count($splashPages) ?>
		<?php if ($pageCount > 0): ?>
			<li class="level0 nav-<?php echo 1 + $this->getCategoryIndexOffset() ?> level-top parent">
				<a href="#" class="level-top"><span><?php echo $this->escapeHtml($this->getGroupedTitle()) ?></span></a>
				<ul class="level0">
				<?php $pageIt = 1 ?>
				<?php foreach($splashPages as $splashPage): ?>
					<li class="level1 nav-<?php echo 1 + $this->getCategoryIndexOffset() ?>-<?php echo $pageIt ?><?php if ($pageIt == 1): ?> first<?php endif; ?><?php if ($pageIt == $pageCount): ?> last<?php endif; ?>">
						<a href="<?php echo $splashPage->getUrl() ?>" title="<?php echo $this->escapeHtml($splashPage->getName()) ?>"><span><?php echo $this->escapeHtml($splashPage->getName()) ?></span></a>
					</li>
				<?php ++$pageIt; endforeach; ?>
				</ul>
			</li>
		<?php endif; ?>
	<?php else: ?>
		<?php $splashGroups = $this->getSplashGroups() ?>
		<?php $groupCount = count($splashGroups) ?>
		<?php if ($groupCount > 0): ?>
			<?php $groupIt = 1 ?>
			<?php foreach($splashGroups as $splashGroup): ?>
				<li class="level0 nav-<?php echo $groupIt + $this->getCategoryIndexOffset() ?> level-top parent">
					<a href="<?php echo $splashGroup->canDisplay() ? $splashGroup->getUrl() : '#' ?>" class="level-top"><span><?php echo $this->escapeHtml($splashGroup->getName()) ?></span></a>
					<?php $splashPages = $this->getSplashGroupSplashPages($splashGroup) ?>
					<?php $pageCount = count($splashPages) ?>
					<?php $pageIt = 1; ?>
					<?php if ($pageCount > 0): ?>
						<ul class="level0">
						<?php foreach($splashPages as $splashPage): ?>
							<li class="level1 nav-<?php echo $groupIt + $this->getCategoryIndexOffset() ?>-<?php echo $pageIt ?><?php if ($pageIt == 1): ?> first<?php endif; ?><?php if ($pageIt == $pageCount): ?> last<?php endif; ?>">
								<a href="<?php echo $splashPage->getUrl() ?>" title="<?php echo $this->escapeHtml($splashPage->getName()) ?>"><span><?php echo $this->escapeHtml($splashPage->getName()) ?></span></a>
							</li>
						<?php ++$pageIt; endforeach; ?>
						</ul>
					<?php endif; ?>
				</li>
			<?php ++$groupIt; endforeach; ?>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>